// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleModel.Services;

#nullable disable

namespace SampleModel.Migrations
{
  [DbContext(typeof(SampleContext))]
    [Migration("20220711145359_001")]
    partial class _001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("SampleModel.Entity.GroupViewRelation", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupid");

                    b.Property<int>("ViewId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("viewid");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candelete");

                    b.Property<bool>("CanInsert")
                        .HasColumnType("INTEGER")
                        .HasColumnName("caninsert");

                    b.Property<bool>("CanRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("canread");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("canupdate");

                    b.HasKey("GroupId", "ViewId");

                    b.ToTable("tbl_group_view_relations");
                });
#pragma warning restore 612, 618
        }
    }
}
