// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleModel.Services;

#nullable disable

namespace SampleModel.Migrations
{
  [DbContext(typeof(SampleContext))]
    partial class SampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("SampleModel.Entity.GroupInfo", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupid");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("groupname");

                    b.HasKey("GroupId");

                    b.ToTable("tbl_groupinfos");
                });

            modelBuilder.Entity("SampleModel.Entity.GroupViewRelation", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupid");

                    b.Property<int>("ViewId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("viewid");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candelete");

                    b.Property<bool>("CanInsert")
                        .HasColumnType("INTEGER")
                        .HasColumnName("caninsert");

                    b.Property<bool>("CanRead")
                        .HasColumnType("INTEGER")
                        .HasColumnName("canread");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("canupdate");

                    b.HasKey("GroupId", "ViewId");

                    b.ToTable("tbl_group_view_relations");
                });

            modelBuilder.Entity("SampleModel.Entity.UserInfo", b =>
                {
                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("userid");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("groupid");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("tbl_userinfos");
                });

            modelBuilder.Entity("SampleModel.Entity.ViewInfo", b =>
                {
                    b.Property<int>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("viewid");

                    b.Property<string>("ViewName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("viewname");

                    b.HasKey("ViewId");

                    b.ToTable("tbl_viewinfos");
                });
#pragma warning restore 612, 618
        }
    }
}
